<?php
/**
 * @file
 * awards_content.features.inc
 */

/**
 * Implements hook_node_info().
 */
function awards_content_node_info() {
  $items = array(
    'awards' => array(
      'name' => t('Awards'),
      'base' => 'node_content',
      'description' => t('Links to awards'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
